env:
  browser: true
  commonjs: true
  es6: true
  jest: true

extends: ["plugin:react/recommended"]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module

plugins: ["react"]

settings:
  react:
    version: "16"
